import request from 'supertest';
import { describe, expect, it } from 'vitest';
import { createApp } from '../../src/server/app.js';
import { RoomStore } from '../../src/server/room-store.js';
import { AuthStore } from '../../src/server/auth-store.js';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

describe('HTTP room API contracts', () => {
  it('creates and joins a room with reconnect tokens', async () => {
    const store = new RoomStore();
    const app = createApp({ roomStore: store });

    const create = await request(app).post('/api/rooms').send({ nickname: '阿明' }).expect(201);
    expect(create.body.roomCode).toMatch(/^[A-Z0-9]{6,}$/);
    expect(create.body.seatIndex).toBe(0);
    expect(create.body.reconnectToken).toBeTruthy();

    const join = await request(app).post(`/api/rooms/${create.body.roomCode}/join`).send({ nickname: '小红' }).expect(201);
    expect(join.body.seatIndex).toBe(1);
    expect(join.body.reconnectToken).toBeTruthy();
  });

  it('rejects invalid joins, duplicate nicknames, full rooms, and started rooms', async () => {
    const store = new RoomStore();
    const app = createApp({ roomStore: store });

    await request(app).post('/api/rooms/NOPE99/join').send({ nickname: '小红' }).expect(404);
    const create = await request(app).post('/api/rooms').send({ nickname: '阿明' }).expect(201);
    const roomCode = create.body.roomCode as string;
    await request(app).post(`/api/rooms/${roomCode}/join`).send({ nickname: '阿明' }).expect(409);
    await request(app).post(`/api/rooms/${roomCode}/join`).send({ nickname: '小红' }).expect(201);
    await request(app).post(`/api/rooms/${roomCode}/join`).send({ nickname: '小李' }).expect(201);
    await request(app).post(`/api/rooms/${roomCode}/join`).send({ nickname: '小王' }).expect(409);

    const room = store.requireRoom(roomCode);
    room.status = 'in_game';
    store.replaceRoom(room);
    await request(app).post(`/api/rooms/${roomCode}/join`).send({ nickname: '新人' }).expect(409);
  });

  it('reconnect API removed — returns 404', async () => {
    const store = new RoomStore();
    const app = createApp({ roomStore: store });
    const create = await request(app).post('/api/rooms').send({ nickname: '阿明' }).expect(201);
    const roomCode = create.body.roomCode as string;
    // Reconnect endpoint removed (spec 005-room-lobby-join).
    // Socket-level auth handles reconnection automatically.
    await request(app).post(`/api/rooms/${roomCode}/reconnect`).send({ reconnectToken: create.body.reconnectToken }).expect(404);
  });

  it('returns stable Chinese error responses for validation failures', async () => {
    const app = createApp({ roomStore: new RoomStore() });
    // Without auth and with empty/missing nickname, returns UNAUTHORIZED
    const response = await request(app).post('/api/rooms').send({}).expect(401);
    expect(response.body.error.code).toBe('UNAUTHORIZED');
    expect(response.body.error.message).toBeTruthy();
  });

  it('restricts invite code management to admin users', async () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'room-api-test-'));
    const authStore = new AuthStore(tmpDir);
    const app = createApp({ roomStore: new RoomStore(), authStore });

    // Generate a seed invite code for registration
    const seedCode = authStore.generateInviteCode('system');

    // Register first user → automatically becomes admin
    const adminRes = await request(app).post('/api/auth/register').send({
      username: 'admin1',
      password: 'adminpass',
      inviteCode: seedCode.code
    }).expect(201);
    const adminToken = adminRes.body.token as string;
    expect(adminRes.body.user.isAdmin).toBe(true);

    // Admin can generate invite codes
    const genCode = await request(app).post('/api/admin/invite-codes')
      .set('Authorization', `Bearer ${adminToken}`)
      .expect(201);
    expect(genCode.body.code).toBeTruthy();

    // Register second user (not admin — uses code generated by admin1)
    const userRes = await request(app).post('/api/auth/register').send({
      username: 'user1',
      password: 'userpass',
      inviteCode: genCode.body.code
    }).expect(201);
    const userToken = userRes.body.token as string;
    expect(userRes.body.user.isAdmin).toBe(false);

    // Non-admin cannot generate invite codes
    await request(app).post('/api/admin/invite-codes')
      .set('Authorization', `Bearer ${userToken}`)
      .expect(400);

    // Non-admin cannot list invite codes
    await request(app).get('/api/admin/invite-codes')
      .set('Authorization', `Bearer ${userToken}`)
      .expect(400);

    // Cleanup
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });
});
